// <auto-generated />
using System;
using MeetingRoom.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingRoom.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907142102_AddTimeSlotRowVersion")]
    partial class AddTimeSlotRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingRoom.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeetingRooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Capacity = 12,
                            Name = "Conference Room A"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Capacity = 4,
                            Name = "Focus Room B"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Capacity = 20,
                            Name = "Board Room C"
                        });
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeetingRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRoomId", "StartTime")
                        .IsUnique();

                    b.ToTable("TimeSlots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000009"),
                            EndTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000010"),
                            EndTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000011"),
                            EndTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000012"),
                            EndTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000013"),
                            EndTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000014"),
                            EndTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000015"),
                            EndTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0001-000000000016"),
                            EndTime = new DateTime(2024, 1, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            StartTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000009"),
                            EndTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000010"),
                            EndTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000011"),
                            EndTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000012"),
                            EndTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000013"),
                            EndTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000014"),
                            EndTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000015"),
                            EndTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0002-000000000016"),
                            EndTime = new DateTime(2024, 1, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            StartTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000009"),
                            EndTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000010"),
                            EndTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000011"),
                            EndTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000012"),
                            EndTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000013"),
                            EndTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000014"),
                            EndTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000015"),
                            EndTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0003-000000000016"),
                            EndTime = new DateTime(2024, 1, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            MeetingRoomId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            StartTime = new DateTime(2024, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.Booking", b =>
                {
                    b.HasOne("MeetingRoom.Api.Models.TimeSlot", "TimeSlot")
                        .WithOne("Booking")
                        .HasForeignKey("MeetingRoom.Api.Models.Booking", "TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetingRoom.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.TimeSlot", b =>
                {
                    b.HasOne("MeetingRoom.Api.Models.Room", "MeetingRoom")
                        .WithMany("TimeSlots")
                        .HasForeignKey("MeetingRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingRoom");
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.Room", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("MeetingRoom.Api.Models.TimeSlot", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
